In [6]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [7]:
knn = KNeighborsClassifier(n_neighbors=3)

In [8]:
data = pd.read_table('fruit_data_with_colors.txt')

In [9]:
data

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

In [10]:
X = data[['mass','height','width','color_score']]
y = data['fruit_label']

In [11]:
X

mass  height  width  color_score
0    192     7.3    8.4         0.55
1    180     6.8    8.0         0.59
2    176     7.2    7.4         0.60
3     86     4.7    6.2         0.80
4     84     4.6    6.0         0.79
5     80     4.3    5.8         0.77
6     80     4.3    5.9         0.81
7     76     4.0    5.8         0.81
8    178     7.8    7.1         0.92
9    172     7.0    7.4         0.89
10   166     7.3    6.9         0.93
11   172     7.6    7.1         0.92
12   154     7.1    7.0         0.88
13   164     7.7    7.3         0.70
14   152     7.3    7.6         0.69
15   156     7.1    7.7         0.69
16   156     7.5    7.6         0.67
17   168     7.6    7.5         0.73
18   162     7.1    7.5         0.83
19   162     7.2    7.4         0.85
20   160     7.5    7.5         0.86
21   156     7.4    7.4         0.84
22   140     7.1    7.3         0.87
23   170     7.9    7.6         0.88
24   342     9.4    9.0         0.75
25   356     9.2    9.2         0.75
26   362     9.2    9.6         0.74
27   204     9.2    7.5         0.77
28   140     7.1    6.7         0.72
29   160     7.4    7.0         0.81
30   158     7.5    7.1         0.79
31   210     8.0    7.8         0.82
32   164     7.0    7.2         0.80
33   190     8.1    7.5         0.74
34   142     7.8    7.6         0.75
35   150     7.9    7.1         0.75
36   160     7.6    7.1         0.76
37   154     7.3    7.3         0.79
38   158     7.8    7.2         0.77
39   144     7.4    6.8         0.75
40   154     7.5    7.1         0.78
41   180     8.2    7.6         0.79
42   154     7.2    7.2         0.82
43   194    10.3    7.2         0.70
44   200    10.5    7.3         0.72
45   186     9.2    7.2         0.72
46   216    10.2    7.3         0.71
47   196     9.7    7.3         0.72
48   174    10.1    7.3         0.72
49   132     8.7    5.8         0.73
50   130     8.2    6.0         0.71
51   116     7.5    6.0         0.72
52   118     8.0    5.9         0.72
53   120     8.4    6.0         0.74
54   116     8.5    6.1         0.71
55   116     7.7    6.3         0.72
56   116     8.1    5.9         0.73
57   152     8.5    6.5         0.72
58   118     8.1    6.1         0.70

In [12]:
y

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [15]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
knn.score(X_test,y_test)

0.8

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
mm = MinMaxScaler()

In [19]:
X_train = mm.fit_transform(X_train)

In [20]:
X_train

array([[0.28671329, 0.53846154, 0.34210526, 0.63157895],
       [0.1958042 , 0.72307692, 0.        , 0.47368421],
       [0.22377622, 0.47692308, 0.39473684, 0.84210526],
       [0.27972028, 0.52307692, 0.42105263, 0.76315789],
       [0.27272727, 0.50769231, 0.39473684, 0.63157895],
       [0.44755245, 0.8       , 0.44736842, 0.57894737],
       [0.31468531, 0.50769231, 0.28947368, 1.        ],
       [0.13986014, 0.69230769, 0.07894737, 0.42105263],
       [0.23076923, 0.58461538, 0.47368421, 0.52631579],
       [0.14685315, 0.61538462, 0.02631579, 0.44736842],
       [0.30769231, 0.56923077, 0.39473684, 0.39473684],
       [0.40559441, 0.50769231, 0.68421053, 0.        ],
       [0.27972028, 0.47692308, 0.5       , 0.36842105],
       [0.13986014, 0.53846154, 0.05263158, 0.44736842],
       [0.43356643, 1.        , 0.39473684, 0.44736842],
       [0.23776224, 0.52307692, 0.26315789, 0.52631579],
       [0.36363636, 0.64615385, 0.47368421, 0.63157895],
       [0.35664336, 0.58461538,

In [21]:
X_test = mm.transform(X_test)

In [22]:
X_test

array([[0.28671329, 0.58461538, 0.36842105, 0.57894737],
       [0.34965035, 0.49230769, 0.42105263, 0.13157895],
       [0.26573427, 0.50769231, 0.47368421, 0.36842105],
       [0.32167832, 0.55384615, 0.44736842, 0.47368421],
       [0.13986014, 0.63076923, 0.02631579, 0.47368421],
       [0.3006993 , 0.49230769, 0.42105263, 0.78947368],
       [0.33566434, 0.46153846, 0.42105263, 0.89473684],
       [0.27272727, 0.53846154, 0.34210526, 0.60526316],
       [0.14685315, 0.63076923, 0.07894737, 0.39473684],
       [0.30769231, 0.46153846, 0.36842105, 0.65789474],
       [0.32867133, 0.6       , 0.47368421, 0.86842105],
       [0.27272727, 0.49230769, 0.36842105, 0.71052632],
       [0.29370629, 0.52307692, 0.31578947, 0.68421053],
       [0.41958042, 0.87692308, 0.39473684, 0.44736842],
       [0.93006993, 0.83076923, 0.84210526, 0.52631579]])

In [23]:
knn = KNeighborsClassifier(n_neighbors=3)

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [25]:
knn.score(X_test,y_test)

0.8666666666666667

In [26]:
knn.predict(X_test)

array([3, 1, 1, 3, 4, 1, 1, 3, 4, 3, 1, 1, 3, 4, 3], dtype=int64)

In [27]:
y_test

38    3
2     1
14    1
17    1
56    4
19    1
9     1
40    3
58    4
32    3
23    1
42    3
29    3
47    4
24    3
Name: fruit_label, dtype: int64

In [28]:
from sklearn.neighbors import KNeighborsRegressor

In [29]:
knn = KNeighborsRegressor(n_neighbors=3)

In [30]:
from sklearn.datasets import load_boston

In [31]:
data = load_boston()

In [32]:
X, y = load_boston(return_X_y=True)

In [33]:
X.shape

(506, 13)

In [34]:
y.shape

(506,)

In [35]:
print(load_boston()['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [38]:
knn.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [39]:
knn.score(X_test,y_test)

0.5189042653818366